### ISSUE TITLE
Authenticated requests fail

### ISSUE THREAD

**Issue by ddeboer** [Ontotext-AD/graphdb.js#123]
**Library version [e.g. 1.1.2]**

1.6.0-RC2

**Node.js version [e.g. 8.16.0]**

v15.4.0

**Describe the bug**

GraphDB returns `Request method 'POST' not supported` for authenticated requests.

**To Reproduce**

This works:

```javascript
const config = new graphdb.repository.RepositoryClientConfig([url]);
const repository = new graphdb.repository.RDFRepositoryClient(config);
await repository.addQuads(my_quads);
```

But this doesn’t:

```javascript
const config = new graphdb.repository.RepositoryClientConfig([url]);
config.setUsername('my_username');
config.setPass('my_password');
const repository = new graphdb.repository.RDFRepositoryClient(config);
await repository.addQuads(my_quads);
```

Throws:

```
Error: Request failed with status code 405
    at createError (/Users/david/src/netwerk-digitaal-erfgoed/registry-api/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/david/src/netwerk-digitaal-erfgoed/registry-api/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/david/src/netwerk-digitaal-erfgoed/registry-api/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (node:events:388:22)
    at endReadableNT (node:internal/streams/readable:1295:12)
    at processTicksAndRejections (node:internal/process/task_queues:80:21)
```

**Expected behavior**

Both unauthenticated and authenticated requests to GraphDB should work.

**Additional context**

**Comment by teodossidossev** [comment]
@ddeboer, thank you for the issue, it is planned for this sprint

**Comment by ddeboer** [comment]
@teodossidossev Awesome! The cause of the bug (if you haven’t already found it) is that authentication requests go to the repository URL (e.g. `http://localhost:7200/repositories/my_repository/rest/login`) while they should go to the main endpoint URL (`http://localhost:7200/rest/login`).

**Comment by teodossidossev** [comment]
The bug fix predetermines refactoring of the server and client configurations, as well as the server and client implementations. I will release an MP with the fix, and then another MR with code refactor, which will most likely lead to a major release version.
