### ISSUE TITLE
issues with typescript types

### ISSUE THREAD

**Issue by antonkulaga** [Ontotext-AD/graphdb.js#142]
I am having big issues with types. Many properties and methods are not properly represented in graphdb/lib/types , for example, method .registerParser does not exist in RDFRepositoryClient type definition despite existing inside RDFRepositoryClient class.
Please, check usability of the library from typescript.

**Comment by teodossidossev** [comment]
Thank you for your issue. It will be planned for the next sprint.

**Comment by antonkulaga** [comment]
Any updated?
