### ISSUE TITLE
update dependencies (esp. N3)

### ISSUE THREAD

**Issue by antonkulaga** [Ontotext-AD/graphdb.js#143]
Many of your dependencies are quite old (for example 1.7.x version of n3). In N3 types support starts from 1.8.0

**Comment by teodossidossev** [comment]
Thank you for your issue. It will be planned for the next sprint.

**Comment by teodossidossev** [comment]
N3 updated 
https://github.com/Ontotext-AD/graphdb.js/pull/157/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R90
