### ISSUE TITLE
Error: connect ECONNREFUSED ::1:7200

### ISSUE THREAD

**Issue by LalitSinghRana** [Ontotext-AD/graphdb.js#165]
**Library version 2.0.2**

**Node.js version 18.3.0**

**Describe the bug**
Getting "Error: connect ECONNREFUSED" when trying to connect to 'http://localhost:7200'. Running code example from npmjs.com readme file.

**To Reproduce**

- Copy -paste code from readme. 
- Run graphdb local server.
- Replace 'http://rdf4j-compliant-server/' with 'http://localhost:7200'

For example : 

`
const { ServerClient, ServerClientConfig } = require('graphdb').server;
const { RDFMimeType } = require('graphdb').http;

const serverConfig = new ServerClientConfig('http://localhost:7200')
	.setTimeout(5000)
	.setHeaders({
		Accept: RDFMimeType.SPARQL_RESULTS_JSON,
	})
	.setKeepAlive(true);

const server = new ServerClient(serverConfig);

server
	.getRepositoryIDs()
	.then((ids) => {
		// work with ids
    console.log(ids);
	})
	.catch((err) => console.log(err));
`

**Expected behavior**
Idk, I guess make connection to db server and not throw error.

**Additional context**

**Comment by LalitSinghRana** [comment]
For a temporary work around, instead of 'http://localhost:7200/' you can use "http://127.0.0.1:7200/". I'm not sure why one is working and other isn't. As far as I can tell localhost is resolved to 127.0.0.1 during lookup.

**Comment by svilenvelikov** [comment]
Hello Lalit. Is it possible for you to try the above example with node.js
16 or below? We havent tested the library with the latest node.js versions
and its possible that there are might have some breaking changes.
