### ISSUE TITLE
npm WARN deprecated uuid@3.4.0: 

### ISSUE THREAD

**Issue by charlesivie** [Ontotext-AD/graphdb.js#189]
When running `npm install graphdb` I get the following warning:
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

**Comment by svilenvelikov** [comment]
Thank you @charlesivie for reporting this. We know about this as well as a bunch of other rather old dependencies we use. We are going to prioritize the task for upgrading and testing for compatibility.

**Comment by svilenvelikov** [comment]
https://github.com/Ontotext-AD/graphdb.js/pull/196
