### ISSUE TITLE
Manage GraphDB repositories 

### ISSUE THREAD

**Issue by desislava-hristova-ontotext** [Ontotext-AD/graphdb.js#25]
GraphDB Rest API for Repository management has endpoints to:
* create repository using repository config (ttl/json)
* get repository config for existing repo (ttl/json)
* get default repository config for a certain repo type

We need to implement these in the GraphDBServerClient.

Sample model here:
https://www.lucidchart.com/documents/edit/00dd0ddf-7aa6-4fcc-8d0a-b631340d7d1b/1?shared=true&
See also webapi -> repository-management-controller

**Comment by OR13** [comment]
This issue implies there is no way to create a repo using the graphdb.js npm module... It was not immediately obvious how to create repo using the npm module.

**Comment by svilenvelikov** [comment]
> This issue implies there is no way to create a repo using the graphdb.js npm module... It was not immediately obvious how to create repo using the npm module.

Yes, your observation is correct. Currently graphdb.js doesn't support repository management operations. We probably should have described it in the readme. I'll update it to avoid such confusions until this issue is completed.

**Comment by teodossidossev** [comment]
GraphDBServerClient is now implemented and allows CRUD operations with repositories and users and will be introduced with release 2.0. See the project's documentation.
