### ISSUE TITLE
Get authentication from a secured GDB server (login/logout)

### ISSUE THREAD

**Issue by desislava-hristova-ontotext** [Ontotext-AD/graphdb.js#26]
Add GraphDBServerClient that depends on GDB APIs for login/logout.
Login sends request to /rest/login/** and returns the jwt user and Authorization header. So we need to attach this header to each request afterwords.
Logout should disallow this header.

Token validity is configured using graphdb.auth.token.validity property and by default is 30 days. When the token expired 409:Authentication session expired is returned. Introduce an option to configure whether we obtain new token for re-auth when the token expired or return the error to the user.

**Comment by estathop** [comment]
code example please ?
