### ISSUE TITLE
Upgrade to GDB latest release (9.0)

### ISSUE THREAD

**Issue by desislava-hristova-ontotext** [Ontotext-AD/graphdb.js#58]
Upgrade and test against GDB 9.5

**Comment by teodossidossev** [comment]
upgrage to GDB 9.3.0 
https://github.com/Ontotext-AD/graphdb.js/releases/tag/v1.3.0
https://github.com/Ontotext-AD/graphdb.js/pull/95

**Comment by teodossidossev** [comment]
upgrage to GDB 9.4.0
https://github.com/Ontotext-AD/graphdb.js/releases/tag/v1.4.0
https://github.com/Ontotext-AD/graphdb.js/pull/99

**Comment by teodossidossev** [comment]
upgrage to GDB 9.5.0
https://github.com/Ontotext-AD/graphdb.js/releases/tag/v1.5.0
https://github.com/Ontotext-AD/graphdb.js/pull/100
