### ISSUE TITLE
Tutorials are outdated

### ISSUE THREAD

**Issue by estathop** [Ontotext-AD/graphdb.js#91]
**Library version 1.2.1**

**Node.js version 15**

**Describe the bug**
the problem was in the repository.upload() method when you suggest in the tutorials to follow ( stream, null, null, contenttype) when in reality after checking your official up-to-dated documentation it only needed (stream, contentType) as other inputs are optional

**Comment by teodossidossev** [comment]
MR https://github.com/Ontotext-AD/graphdb.js/pull/104
